services:
  mongodb:
    image: 'mongo:latest'
#    environment:
#      - 'MONGO_INITDB_DATABASE=mydatabase'
#      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
#      - 'MONGO_INITDB_ROOT_USERNAME=root'
    env_file:
      - .env
    environment:
        MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - '27017'
