services:
  mongodb:
    image: 'mongo:latest'
    env_file:
      - .env
    environment:
        MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - '27017'
