services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD='
      - 'MONGO_INITDB_ROOT_USERNAME='
    ports:
      - "27017:27017"
