spring:
  application:
    name: StockForecastingAndSecureManagement
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}

server:
  port: ${SERVER_PORT:8082}

app:
  jwtSecret: ${APP_JWT_SECRET}
  jwtExpirationMs: ${APP_JWT_EXPIRATION_MS:86400000}
