spring:
  application:
    name: StockForecastingAndSecureManagement
  profiles:
    active: dev

server:
  port: 8083

app:
  jwtExpirationMs: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha
    default-models-expand-depth: 1
