spring:
  application:
    name: StockForecastingAndSecureManagement
  mongodb:
    uri: mongodb://root:secret@localhost:27017/SFASM?authSource=admin
app:
  jwtSecret: ${APP_JWT_SECRET:sqbddsjvqfhjskhlfdskjlhfdlskqgfsldbfhkdskflhsdhklfsqdhkfgqhsdklfhk}
  jwtExpirationMs: 86400000
server:
  port: 8082