spring:
  application:
    name: StockForecastingAndSecureManagement
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/SFASM}
app:
  jwtSecret: ${APP_JWT_SECRET:sqbddsjvqfhjskhlfdskjlhfdlskqgfsldbfhkdskflhsdhklfsqdhkfgqhsdklfhk}
  jwtExpirationMs: 86400000